name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: |
          uv pip install --system --no-cache-dir .[dev]
      - name: Ruff
        run: |
          uv tool run ruff check src tests
      - name: Tests
        run: |
          uv tool run pytest
